name: bookandmeet
description: An appointment app for beauty service providers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  flex_color_scheme: ^7.3.1
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  icons_plus: ^5.0.0
  google_fonts: ^6.1.0
  pinput: ^3.0.1

  # services
  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.12
  get_it: ^7.6.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  #state management
  signals: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
